'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const C=require('../js/core.js');
const base=(more={})=>Object.assign({nombre:'Portatil de prueba',codigo:'ACT-001',tipo:'Equipo TI',area:'Tecnolog\u00eda',responsable:'',estado:'Activo',fecha:'2026-01-10',valor:2500000,obs:'Datos ficticios'},more);
function fixture(){const s=new C.Store();const id=s.saveAsset(base());return {s,id};}
function assignment(id,more={}){return Object.assign({activoId:id,colaborador:'Colaborador Demo',cedula:'10000001',area:'Ventas',fecha:'2026-02-01',obs:''},more);}
function maintenance(id,more={}){return Object.assign({activoId:id,tipo:'Preventivo',tecnico:'Tecnico Demo',fecha:'2026-03-01',estado:'Pendiente',desc:'Limpieza y revision'},more);}
test('UT-01 | Inicio sin registros y esquema valido',()=>{const s=new C.Store();assert.equal(s.state.activos.length,0);assert.ok(C.verifyState(s.state));});
test('UT-02 | Crear activo y registrar alta',()=>{const {s,id}=fixture();assert.equal(s.state.activos[0].id,id);assert.equal(s.state.movs[0].tipo,'Alta');});
test('UT-03 | Nombre obligatorio',()=>{assert.throws(()=>new C.Store().saveAsset(base({nombre:''})),/Nombre/);});
test('UT-04 | Codigo obligatorio y minimo de caracteres',()=>{assert.throws(()=>new C.Store().saveAsset(base({codigo:'A'})),/digo/);});
test('UT-05 | Rechazar codigo duplicado normalizado',()=>{const {s}=fixture();assert.throws(()=>s.saveAsset(base({codigo:' act-001 '})),/ya existe/);assert.equal(s.state.activos.length,1);});
test('UT-06 | Tipo obligatorio',()=>{assert.throws(()=>new C.Store().saveAsset(base({tipo:''})),/Tipo/);});
test('UT-07 | Area obligatoria',()=>{assert.throws(()=>new C.Store().saveAsset(base({area:''})),/selecciona/);});
test('UT-08 | Rechazar valor negativo',()=>{assert.throws(()=>new C.Store().saveAsset(base({valor:-1})),/Valor/);});
test('UT-09 | Rechazar valor no numerico',()=>{assert.throws(()=>new C.Store().saveAsset(base({valor:'abc'})),/Valor/);});
test('UT-10 | Fecha obligatoria',()=>{assert.throws(()=>new C.Store().saveAsset(base({fecha:''})),/fecha/);});
test('UT-11 | Rechazar fecha de calendario inexistente',()=>{assert.throws(()=>new C.Store().saveAsset(base({fecha:'2026-02-30'})),/fecha/);});
test('UT-12 | Editar conserva ID y no duplica el registro',()=>{const {s,id}=fixture();s.saveAsset(base({nombre:'Portatil actualizado'}),id);assert.equal(s.state.activos.length,1);assert.equal(s.state.activos[0].nombre,'Portatil actualizado');assert.equal(s.state.movs.length,2);});
test('UT-13 | Historial permanece vinculado al ID tras renombrar',()=>{const {s,id}=fixture();s.saveAsset(base({nombre:'Equipo renombrado'}),id);assert.equal(s.state.movs.filter(m=>m.activoId===id).length,2);});
test('UT-14 | Asignacion actualiza estado responsable y area',()=>{const {s,id}=fixture();s.assign(assignment(id));const a=s.state.activos[0];assert.equal(a.estado,'Asignado');assert.equal(a.responsable,'Colaborador Demo');assert.equal(a.area,'Ventas');});
test('UT-15 | Rechazar doble asignacion del mismo activo',()=>{const {s,id}=fixture();s.assign(assignment(id));assert.throws(()=>s.assign(assignment(id)),/disponible/);assert.equal(s.state.asigns.length,1);});
test('UT-16 | Cedula debe ser numerica',()=>{const {s,id}=fixture();assert.throws(()=>s.assign(assignment(id,{cedula:'abcd12'})),/dula/);});
test('UT-17 | Colaborador obligatorio',()=>{const {s,id}=fixture();assert.throws(()=>s.assign(assignment(id,{colaborador:''})),/Colaborador/);});
test('UT-18 | Asignacion posterior o igual al ingreso',()=>{const {s,id}=fixture();assert.throws(()=>s.assign(assignment(id,{fecha:'2025-01-01'})),/anterior/);});
test('UT-19 | Devolucion libera activo y conserva historial',()=>{const {s,id}=fixture();const as=s.assign(assignment(id));s.returnAssignment(as,'2026-02-02');assert.equal(s.state.activos[0].estado,'Activo');assert.equal(s.state.activos[0].responsable,'');assert.equal(s.state.asigns[0].estado,'Devuelto');});
test('UT-20 | Rechazar devolucion repetida',()=>{const {s,id}=fixture();const as=s.assign(assignment(id));s.returnAssignment(as,'2026-02-02');assert.throws(()=>s.returnAssignment(as,'2026-02-03'),/ya fue/);});
test('UT-21 | Rechazar devolucion anterior a asignacion',()=>{const {s,id}=fixture();const as=s.assign(assignment(id));assert.throws(()=>s.returnAssignment(as,'2026-01-15'),/anterior/);});
test('UT-22 | No dar de baja activo asignado',()=>{const {s,id}=fixture();s.assign(assignment(id));assert.throws(()=>s.retireAsset(id),/disponible/);});
test('UT-23 | Impedir cambio directo que rompa asignacion',()=>{const {s,id}=fixture();s.assign(assignment(id));assert.throws(()=>s.saveAsset(base(),id),/Primero/);});
test('UT-24 | No crear un activo como asignado sin registro',()=>{assert.throws(()=>new C.Store().saveAsset(base({estado:'Asignado'})),/m.dulos/);});
test('UT-25 | Registrar mantenimiento cambia estado',()=>{const {s,id}=fixture();s.maintenance(maintenance(id));assert.equal(s.state.activos[0].estado,'Mantenimiento');});
test('UT-26 | Tecnico obligatorio',()=>{const {s,id}=fixture();assert.throws(()=>s.maintenance(maintenance(id,{tecnico:''})),/cnico/);});
test('UT-27 | Descripcion de mantenimiento obligatoria',()=>{const {s,id}=fixture();assert.throws(()=>s.maintenance(maintenance(id,{desc:''})),/Descripci/);});
test('UT-28 | No abrir mantenimiento sobre activo asignado',()=>{const {s,id}=fixture();s.assign(assignment(id));assert.throws(()=>s.maintenance(maintenance(id)),/devuelve/);});
test('UT-29 | Impedir dos mantenimientos simultaneos',()=>{const {s,id}=fixture();s.maintenance(maintenance(id));assert.throws(()=>s.maintenance(maintenance(id)),/libera/);});
test('UT-30 | Completar mantenimiento libera activo',()=>{const {s,id}=fixture();const m=s.maintenance(maintenance(id));s.closeMaintenance(m,'Completado','2026-03-02');assert.equal(s.state.activos[0].estado,'Activo');assert.equal(s.state.mants[0].estado,'Completado');});
test('UT-31 | Cancelar mantenimiento conserva registro y libera',()=>{const {s,id}=fixture();const m=s.maintenance(maintenance(id));s.closeMaintenance(m,'Cancelado','2026-03-02');assert.equal(s.state.activos[0].estado,'Activo');assert.equal(s.state.mants.length,1);});
test('UT-32 | No cerrar dos veces el mantenimiento',()=>{const {s,id}=fixture();const m=s.maintenance(maintenance(id));s.closeMaintenance(m,'Completado','2026-03-02');assert.throws(()=>s.closeMaintenance(m,'Completado','2026-03-03'),/cerrado/);});
test('UT-33 | Baja logica conserva activo e historial',()=>{const {s,id}=fixture();s.retireAsset(id);assert.equal(s.state.activos.length,1);assert.equal(s.state.activos[0].estado,'Baja');assert.equal(s.state.movs[0].tipo,'Baja');});
test('UT-34 | No asignar activo dado de baja',()=>{const {s,id}=fixture();s.retireAsset(id);assert.throws(()=>s.assign(assignment(id)),/disponible/);});
test('UT-35 | Reporte combina rango area y estado',()=>{const {s}=fixture();s.saveAsset(base({codigo:'ACT-002',area:'Ventas',fecha:'2026-04-01'}));assert.equal(C.report(s.state,{desde:'2026-01-01',hasta:'2026-03-01',area:'Tecnolog\u00eda',estado:'Activo'}).length,1);});
test('UT-36 | Reporte rechaza rango de fechas invertido',()=>{const {s}=fixture();assert.throws(()=>C.report(s.state,{desde:'2026-03-01',hasta:'2026-01-01'}),/inicial/);});
test('UT-37 | CSV conserva cero y escapa comillas',()=>{const raw=C.csv([base({valor:0,nombre:'Equipo "Demo"'})]);assert.ok(raw.startsWith('\uFEFF'));assert.ok(raw.includes('"Equipo ""Demo"""'));assert.ok(raw.includes('"0"'));});
test('UT-38 | CSV neutraliza texto que inicia como formula',()=>{const raw=C.csv([base({nombre:'=1+1'})]);assert.ok(raw.includes('"\'=1+1"'));});
test('UT-39 | Preferencias se guardan en la transaccion',()=>{const {s}=fixture();s.saveConfig({nombre:'Usuario de Pruebas',notificaciones:'Desactivadas'});assert.equal(s.state.config.nombre,'Usuario de Pruebas');});
test('UT-40 | Respaldo valido se puede restaurar',()=>{const {s}=fixture();const dest=new C.Store();dest.replace(s.state);assert.equal(dest.state.activos.length,1);});
test('UT-41 | Rechazar version de respaldo incompatible',()=>{assert.throws(()=>new C.Store({version:1}),/versi/);});
test('UT-42 | Rechazar respaldo con referencia huerfana',()=>{const {s,id}=fixture();s.assign(assignment(id));const snap=s.state;snap.activos=[];assert.throws(()=>C.verifyState(snap),/sin activo/);});
test('UT-43 | Rechazar identificador peligroso en respaldo',()=>{const {s}=fixture();const snap=s.state;snap.activos[0].id="x');alert(1)//";assert.throws(()=>C.verifyState(snap),/Identificador/);});
test('UT-44 | Fallo de escritura no confirma ni muta el estado',()=>{const s=new C.Store(C.initial(),()=>{throw new Error('Cuota agotada');});const before=s.state;assert.throws(()=>s.saveAsset(base()),/Cuota/);assert.deepEqual(s.state,before);});
test('UT-45 | Lectura del estado devuelve copia defensiva',()=>{const {s}=fixture();const copy=s.state;copy.activos[0].nombre='Alterado';assert.notEqual(s.state.activos[0].nombre,'Alterado');});
test('UT-46 | Persistencia detecta conflicto entre pestanas',()=>{let raw=null;const storage={getItem:()=>raw,setItem:(_,v)=>{raw=v;}};const a=new C.Store(C.initial(),C.storageWriter(storage));const b=new C.Store(C.initial(),C.storageWriter(storage));a.saveAsset(base());assert.throws(()=>b.saveAsset(base({codigo:'ACT-002'})),/otra pesta/);});
test('UT-47 | Texto con etiquetas se conserva como dato, no se ejecuta en dominio',()=>{const {s}=fixture();s.saveAsset(base({codigo:'ACT-002',nombre:'<img src=x onerror=alert(1)>'}));assert.equal(s.state.activos[0].nombre,'<img src=x onerror=alert(1)>');});
test('UT-48 | No editar activo inexistente',()=>{assert.throws(()=>new C.Store().saveAsset(base(),'ausente'),/no existe/);});
